Login & Register
IdjiotSandwiches/envirostore pull request #18
Opened 2024-10-15 09:38 UTC by IdjiotSandwiches

2024-10-17 16:01 UTC, appleaze commented on resources/views/component/navigation/navbar.blade.php
Navigation to login and register still error

2024-10-17 16:02 UTC, appleaze commented on resources/views/errors/404.blade.php
Ini masuk lewat mana?

2024-10-17 16:05 UTC, appleaze requested changes
Pass certain test case(more on):
https://docs.google.com/spreadsheets/d/1_q1dk5ZqnBbrM0XEZEwz5iAEXABKyBqfMC3KVDjv0-s/edit?gid=1675701385#gid=1675701385

2024-10-18 01:59 UTC, IdjiotSandwiches commented on resources/views/errors/404.blade.php
ini coba masuk ke route yg g ad aj

2024-10-18 02:00 UTC, IdjiotSandwiches commented on resources/views/component/navigation/navbar.blade.php
bentar gw benerin dlu conflict ny

2024-10-18 06:41 UTC, appleaze approved these changes

2024-10-18 06:49 UTC, merged